### ISSUE TITLE
Normes pour les xml:id. #1

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#1]
Bonjour, 

Je ne comprends pas très bien la construction de l'identifiant en xml:id. D'après le modèle ODD, il est "composé du mot-clé ‘ed’ pour une édition numérisée, ‘ms’ pour une transcription de manuscrit, ‘crit’ pour une édition critique ; du nom du texte, sous une forme standard ; et du sigle du manuscrit, ou celui attribué au texte critique ou, pour une édition, du nom de famille du premier éditeur suivi d'un tiret et de la date". 
Comment determiner la forme strandard du nom du texte? ou selon quel référenciel? Combien de lettres du nom doit-on prendre? à quel endroit place-t-on des majuscules? De même, pour identifier une version numérisée, il faut faire référence au nom de l'éditeur avec la date. Or, pour l'exemple du texte de Gui de Bourgogne, l'xml:id est le suivant : ed_GuiBourgG. Il me semble qu'il ne suit pas les normes établis dans le modèle ODD. 
Quelqu'un pourrait-il éclaircir ce point, s'il vous plait? 
Merci

**Comment by ajaniak** [comment]
Les filles, 

Je peux apporter un premier élément de réponse à mes questions #1. Dans le fichier de métadonnées, il y a une liste d'ID: 
ed_MortAymC
ed_DoonRocheM
ed_HuonG
ed_AimeriD

Cela ne répond pas tout à fait à nos interrogations par rapport au modèle ODD, mais cela nous permet d'avancer pour les xml:id et le nommage des fichiers.

**Comment by DUREAULT** [comment]
Bonjour Monsieur @Jean-Baptiste-Camps,

Nous nous demandions également comment définir l'xml:id dans la balise <biblStruct> dans le cas où il y a plusieurs éditeurs (Doon de la Roche, Huon de Bordeaux). 

Merci à vous, 

Ella Duréault.

**Comment by Jean-Baptiste-Camps** [comment]
Bon, il faut que je corrige le modèle ODD. J'ai mis les identifiants tout prêts dans le fichier de métadonnées, ce sont ceux là qu'il faut reprendre.
