### ISSUE TITLE
Pull request pour réunir mon repository et le repository initial

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/geste#10]
Les filles, 

Avec @PonteIneptique nous avons nettoyé mon repository des fichiers .DS_Store qui posaient problème. Mon repository contient désormais un fichier gitignore qui ignore les fichiers .DS_Store et est donc en avance sur le repository original. Pour ne pas avoir de conflits entre nous une fois que chacune mettra son travail sur le repository original, il faut : 
- que je fasse une pull request depuis mon repository vers le repository original, 
- que vous l'acceptiez 
- puis que vous synchronisiez votre repository forké avec le repository original. cf. https://help.github.com/articles/configuring-a-remote-for-a-fork/
et https://help.github.com/articles/syncing-a-fork/

J'ai toutefois encore un problème : mon repository forké contient l'ancien modèle ODD. Il devrait donc y avoir un conflit. Je propose donc de replacer manuellement le nouveau modèle ODD puis de proposer ensuite la pull request.

Merci et mes plus plates excuses pour ce contretemps !
Ella.

**Comment by ArmaneJM** [comment]
Je m’occupe de ça dès mon retour dimanche. Merci pour les précisions !

**Comment by DUREAULT** [comment]
#3 
Petit rappel : suite au changement du modèle ODD, veuillez vérifier que vos fichiers de métadonnées sont conformes et valides. 

Merci, 
Ella.

**Comment by ajaniak** [comment]
C'est bon pour moi.
