### ISSUE TITLE
Répartition des structures des textes

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#12]
Les filles, 

Je propose que l'on commence à encoder les structures des textes puisque 3 des 4 fichiers sont à jour sur les métadonnées #3 . Comment souhaitez-vous vous répartir les textes?

**Comment by DUREAULT** [comment]
Coucou Axelle, 

Je te propose que nous commencions par l'encodage du front : puisque AymeriD n'en a pas, il y a trois front à encoder : 
-AymeriC
-Doon de la Roche
-Huon de Bordeaux 
Je me propose pour l'encodage de Doon de la Roche.

**Comment by ajaniak** [comment]
Dans ce cas, je vais faire le front d'AymeriC!

**Comment by ajaniak** [comment]
Bonjour, 

Quelqu'un aurait-il une solution pour intégrer les <lb/> de manière intelligente afin de conserver l'imitation de l'imprimé? Merci

**Comment by ArmaneJM** [comment]
Je continue donc avec Huon de Bordeaux. Pardonnez mon retard...

**Comment by ajaniak** [comment]
Les filles, j'ai terminé le front de ed_MortAymC. Il y a quelques éléments à revoir et possiblement un peu d'uniformisation à faire par rapport à vos encodages, en particulier au niveau de la présence des vers dans l'introduction.

**Comment by ArmaneJM** [comment]
Je me permet de fermer cette issue qui n'a plus lieu d'être :)
