### ISSUE TITLE
Encodage des images & facs-similés

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/geste#13]
Bonjour les filles & @Jean-Baptiste-Camps, 

Concernant la mise en page, je me demandais s'il fallait faire référence aux bandeaux et lettrines de l'édition imprimée ou simplement aux facs-similés par page ? Et si oui, peut-on citer les URLs ?

Merci,

**Comment by Jean-Baptiste-Camps** [comment]
Laissez tomber bandeaux et lettrines, gardez juste la structuration intellectuelle. Pour les pages, vous pouvez utiliser l'`@facs` des `<pb/>` pour pointer vers le fac-similé.

**Comment by DUREAULT** [comment]
@Jean-Baptiste-Camps 
Dans la suite de ces questions sur les images, 
comment fait-on pour les stemmas ?

Merci  !

**Comment by Jean-Baptiste-Camps** [comment]
Bon, il y a des moyens de les encoder en TEI, si vous vous en sentez (cf. Guidelines, 19 Graphs, Networks, and Trees). Sinon, un fichier image avec `figure` et `graphic`.

**Comment by ajaniak** [comment]
Pardon @Jean-Baptiste-Camps, je ne retrouve pas la réalisation de l'encodage du stemma dans l'odd. 
Est-il possible qu'il ne le prenne pas en compte ? 
Les filles j'ai préféré prendre le modèle tree qui permet une plus grand choix d'attributs de caractérisations des éléments parents/enfants, tandis que le eTree même s'il peut être typé n'en a pas. Dites-moi si ce que vous en pensez.

**Comment by Jean-Baptiste-Camps** [comment]
C'est normal, il faut que je l'y ajoute, car le cas ne s'est pas encore présenté. Si vous créez un ticket, je le ferai, mais ne vous inquiétez pas pour l'erreur de validité pour le moment !

**Comment by ajaniak** [comment]
Bonjour @Jean-Baptiste-Camps,

ma question est liée à la validité de l'xml:id d'un des éléments du stemma. En effet, l'un des manuscrits est nommé O'. Je pensais l'échapper. J'ai trouvé comme code pour l'apostrophe : &#39; . 
Résolvons-nous le problème de cette manière? et est-ce que je peux utiliser ce code ou l'avez-vous déjà formalisé autrement? si ce n'est pas le cas, dois-je le déclarer dans l'en-tête de l'xml? 

Merci

**Comment by Jean-Baptiste-Camps** [comment]
Pas encore rencontré le cas ! Peut-être que pour l'@xml:id, une solution serait carrément de contourner le problème en l'appellant Oprime (par exemple).

**Comment by ajaniak** [comment]
C'est en effet une solution plus simple. Merci

**Comment by ajaniak** [comment]
Cette issue est reprise dans #39 de manière plus spécifique. Je clos donc celle-ci.
