### ISSUE TITLE
encodage imitatif? 

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#14]
Bonjour les filles et @Jean-Baptiste-Camps,

Je voulais savoir quel niveau de finesse nous devions adopter pour l'encodage imitatif de l'imprimé. Devons-nous rendre les italiques, les indices pour les siècles et autres conventions d'écritures? 

Merci

**Comment by DUREAULT** [comment]
Les filles & @Jean-Baptiste-Camps, 

Dans le prolongement de cette question, je me demandais comment vous encodiiez les notes : 
- juste après la portion de texte concernée ?
- ou, conformément à l'édition imprimée, dans un paragraphe suivant le corps de texte principal ? 

Merci et bonne soirée

**Comment by Jean-Baptiste-Camps** [comment]
Ne vous embêtez pas avec le typographique détaillé et pensez en termes sémantiques: si quelque chose est un titre, alors éventuellement `<title>`, mais pas particulièrement `<hi rend='italics'>`. Si vous manquez de temps pour ce type d'encodage, ce n'est pas très grave.

De même, pour les notes, elles vont juste après la portion de texte concerné,
````xml
    comme l'indique M. Dupont<note>Dans son ouvrage, <bibl>M. Dupont, op. cit., p. 32</bibl></note>
````

**Comment by DUREAULT** [comment]
Bonsoir @Jean-Baptiste-Camps ,

Dans la suite de cette question sur le modèle imitatif -et au risque de paraître extrêmement feignante-, dans le front, faut-il respecter la structure : 
-div
-pb
-p
-lb
Ou peut-on se passer des <lb/> ? 
En effet, si nous devons respecter la mise en page de l'édition d'origine, je ne vois pas comment construire de regex pour simplifier l'encodage et cela risque d'être finalement assez long. 

Merci,

**Comment by DUREAULT** [comment]
J'avais pensé à compter le nombre de caractères par ligne exceptées pour celles où il y a une tabulation ou une interruption (fin ou début de paragraphe).

**Comment by ajaniak** [comment]
Ella, ça ne marche pas pour mon édition. 
Il y aurait peut-être moyen de récuperer au moins le découpage en paragraphes de la version html et de le convertir en div, à défaut d'avoir les lb.

**Comment by Jean-Baptiste-Camps** [comment]
C'est-à-dire que vous avez normalement les `div`, les `p` et les `br` dans le document HTML.

Ce qui compte avant tout, ce sont les divisions logiques. Les pages seraient bien aussi, mais elles existent déjà, sous forme de `div` dans les sources html.

**Comment by DUREAULT** [comment]
Merci !
En ce cas, nous reprenons la structure HTML en modifiant les <br> en <lb/> et en rajoutant un au début de chaque paragraphe afin de respecter votre modèle de référence.

**Comment by ajaniak** [comment]
Bonjour @Jean-Baptiste-Camps , 

encore une question, pour l'encodage des vers cités dans les parties liminaires, dois-je type une div ou un p? L'exemple contient un quote mais il ne semble pas prendre en charge des vers. Et je n'ai pas trouvé dans le schéma une réponse univoque à ma question. Merci pour votre réponse.

**Comment by DUREAULT** [comment]
Je signale ici que j'ai rendu les signatures à la fin de l'introduction par un `<p rend="align(right)">Signature</p>`.

**Comment by ajaniak** [comment]
Très bien @DUREAULT je reprends ton schéma pour la signature de mon texte!

**Comment by Jean-Baptiste-Camps** [comment]
Êtes-vous sûre que `quote` ne peut contenir de `l` ?

**Comment by ajaniak** [comment]
Il ne prend pas juste le l, celui-ci doit contenir d'autres balises comme un découpage en mots par exemple. Les filles vous confirmez?

**Comment by ArmaneJM** [comment]
Oui je confirme, il faut y imbriquer au moins une autre balise. Peut être la balise <seg>. Il me semble qu'elle est la plus neutre entre toutes celles proposées. Mais cela me semble peut être un peu artificiel.

**Comment by ArmaneJM** [comment]
Pour revenir la dessus, faut-il faire le découpage de mot pour les `<l>` dans les `<quote>` ?

**Comment by ajaniak** [comment]
Pour ma part j'ai laissé quote tout seul ... en vérité la question n'a pas été tranchée

**Comment by Jean-Baptiste-Camps** [comment]
Oui, laissez les `quote` seuls pour le moment. Je pense qu'il va falloir adapter le modèle pour les introductions. Si vous voulez rendre compte des retours à la ligne, utilisez `lb`, c'est moins sémantique, mais le modèle réserve en fait les vers surtout au corps du document, en considérant que la structuration des front et back est secondaire.
