### ISSUE TITLE
Interrogations sur le typage des divs et leur pertinence

### ISSUE THREAD

**Issue by ArmaneJM** [Chartes-TNAH/geste#16]
Bonjour les filles,

Mon édition (Huon de Bordeaux) comporte un très grand nombre de pages de titres et je me demande si je dois faire une div de type : '''<div type="page_de_titre">''' par page ou si je ne fais qu'une seule div pour contenir l'ensemble de ces pages qui sont en fait toutes à la suite l'une de l'autre. Elles se trouvent de la page 5 (https://fr.wikisource.org/wiki/Page:Anonyme_-_Huon_de_Bordeaux,_chanson_de_geste.djvu/5) à la page 9 (https://fr.wikisource.org/wiki/Page:Anonyme_-_Huon_de_Bordeaux,_chanson_de_geste.djvu/9). 

Merci de me donner votre avis :)

**Comment by ajaniak** [comment]
@ArmaneJM, 

 Il me semble que tu dois toutes les reprendre et doter chacune d'une div propre typer chacune "page_de_titre", du moins c'est ce qui a été fait dans l'exemple de JB Camps.
Je dispose de plusieurs pages de titres également. Si vous décidez de ne pas suivre ce schéma, je m'harmoniserai avec vous.

**Comment by ajaniak** [comment]
Dans le même registre que la question d'Amâne pensez-vous qu'il faille encoder les pages de back concernant la liste des Publications de la Société des anciens textes français?
(https://fr.wikisource.org/wiki/Page:Anonyme_-_La_Mort_Aymeri_de_Narbonne.djvu/300) et (https://fr.wikisource.org/wiki/Page:Anonyme_-_La_Mort_Aymeri_de_Narbonne.djvu/301).
Cela me semble un peu inutile du coup j'avais pensé à éventuellement les indiquer à l'aide de commentaire.

**Comment by DUREAULT** [comment]
Coucou ! Je reviens sur cette issue que je n'avais pas reçue par mail...
Cela dit les mettre en commentaire revient presque au même...
Peut-être peut-on demander l'avis @Jean-Baptiste-Camps ? 

Merci!

**Comment by ajaniak** [comment]
non je ne voulais pas tout encoder! juste indiquer leur existence avec un commentaire

**Comment by DUREAULT** [comment]
Ah d'accord ! Oui effectivement et en ce cas on indiquerait juste les `pb` avec un n° et le lien vers l'image ?

**Comment by ajaniak** [comment]
oui c'est ça

**Comment by ArmaneJM** [comment]
J'ai du coup fait une div par page de titre. La solution du pb avec le lien me semble pertinente pour les listes de publication. @Jean-Baptiste-Camps pourriez vous la confirmer? Merci beaucoup :)

**Comment by Jean-Baptiste-Camps** [comment]
Ça me va.

**Comment by ajaniak** [comment]
Je me permets donc de terminer cette issue puisque nous sommes tous d'accord.
