### ISSUE TITLE
Encodage des body

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#18]
Les filles, 

j'entame l'encodage du body d'ed_MortAymC.xml.

**Comment by ajaniak** [comment]
Est-ce que vous auriez une idée pour encoder rapidement et de manière automatique les notes de bas de pages? Dans la version du html, elles ont été mises en fin de section et non encodée avec les vers. 

Merci!

**Comment by ajaniak** [comment]
Bonjour @Jean-Baptiste-Camps, 

Pourriez-vous nous indiquer une source en mesure de nous renseigner sur la structure des laisses du ed_AimeriD?  Nous ne sommes actuellement en mesure que de rendre les vers. 

Merci

**Comment by ajaniak** [comment]
Du coup @DUREAULT et @ArmaneJM, j'ai commencé à faire le body de ed_AimeriD.

**Comment by DUREAULT** [comment]
D'accord. 
Peut-on récapituler où nous en sommes ? 
Parce que si je comprends : 
-Tu as fini le body de la Mort d'Aymeri, entamé son back + le body de ed_AimeriD ?
-J'ai fini le front de Doon que j'ai pushé vers mon fork (j'aimerai faire encore quelques modifications avant de faire une pull request)
-Et @ArmaneJM ?

**Comment by DUREAULT** [comment]
Je regarde pour les notes de bas de page. 
Et voici peut-être une piste pour Aymeri ? : [http://gallica.bnf.fr/ark:/12148/bpt6k5014h/f9.image.r=demaison,+louis.langFR](url)

**Comment by ajaniak** [comment]
Non, je n'ai pas fini le body d'ed_MortAymC, il faut y intégrer les notes qui dans l'édition sont dans les vers, mais en fin de code pour le html. Je n'ai pas encore trouvé de solution pour leur intégration. 
Le back d'ed_MortAymC est intégré, j'attends la réponse de JB Camps quand on résolution des coquilles. 
Pour ed_AimeriD, le body a seulement été structure avec avec les <l> et les <lb/>. Le découpage en laisse n'étant inconnu, je ne l'ai pas encore fait. 
J'ai pas mal de chose à mettre aussi sur le repository!

**Comment by DUREAULT** [comment]
[http://gallica.bnf.fr/ark:/12148/bpt6k5014h/f9.image.r=demaison,+louis.langFR](url)
Pardon voici le bon lien !

**Comment by DUREAULT** [comment]
Par contre je ne sais pas s'il y a un bug, mais il me semble que les balises ne passent pas quand on les saisit directement mais je suppose que c'est div et vers ?

**Comment by DUREAULT** [comment]
Je regarde pour le HTML du coup !

**Comment by ajaniak** [comment]
non c'était l et lb! je n'ai pas fait de structure générale qu'on aurait pu avoir à refaire.

**Comment by ajaniak** [comment]
Ella le lien était la bonne édition mais seule l'introduction est disponible sur gallica

**Comment by DUREAULT** [comment]
D'accord ! Du coup dans le lien que j'envoyais, il s'agit de la même édition que pour les autres textes avec la structure générale visible, si ça peut aider. 
Pour l'instant, je me prépare à livrer un combat sans merci aux regex.

**Comment by ajaniak** [comment]
écoute j'ai pris des notes sur celles que j'ai utilisées si tu ne t'en sors pas tu pourras tjrs adapter les miennes à l'encodage html du tien.

**Comment by ajaniak** [comment]
Mais le tome 2 de cet ensemble donne le texte!!! victoire

**Comment by DUREAULT** [comment]
C'est gentil ça pour les regex. 
C'est ce que tu cherchais ? Tant mieux alors!
Pour l'instant de mon côté, les notes suivent le texte j'ai l'impression...

**Comment by DUREAULT** [comment]
Mais cela dit, cela pose le même problème si on veut les relier directement dans le texte...

**Comment by ajaniak** [comment]
tu veux dire que les notes sont à la suite du texte de ta page  et pas intégrer dans le texte?

**Comment by DUREAULT** [comment]
Oui !

**Comment by ajaniak** [comment]
Ah mince... Il va falloir trouver une solution à ce problème! Dans ed_GuiBourgG, les notes apparaissent à la suite du texte, mais j'ai l'impression que la version papier suit ce modèle...

**Comment by DUREAULT** [comment]
Attends, rectification pour être bien claire : 
A la suite du texte de chaque page, suivent les notes. 
Donc dans le HTML : texte/notes ; texte/notes pour chaque page (je précise ça un peu bêtement mais je préfère être bien claire !)

**Comment by ajaniak** [comment]
Je me demande si dans ton cas tu ne pourrais pas les encoder comme ça. Cela serait imitatif de l'édition papier.

**Comment by DUREAULT** [comment]
Oui. Pour l'instant, c'est ce que j'ai fait.

**Comment by ajaniak** [comment]
Les lg sont intégrés pour ed_AymeriD

**Comment by Jean-Baptiste-Camps** [comment]
La question des `lg` est-elle résolue, finalement ?

**Comment by ajaniak** [comment]
Oui, je me suis appuyée sur une version numérisée de l'édition présent sur Gallica.

**Comment by ArmaneJM** [comment]
Bonjour les filles, pardonnez moi de répondre si tard j'ai eu des problèmes importants à régler cette semaine. J'ai terminé le front de Huon de Bordeaux et j'entame maintenant le body. Je ne me suis donc pas encore posée la question des notes. Merci d'y avoir d'ores et déjà répondu.

**Comment by DUREAULT** [comment]
Puis-je fermer cette issue ?
Elle me semble résolue !

**Comment by ajaniak** [comment]
oui tu peux!
