### ISSUE TITLE
Encodage du back

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#19]
Bonjour @Jean-Baptiste-Camps, 

Mon édition ed_MortAymC (#12 et #3) possède d'un index. Dans le code html, des corrections de numéro de vers ont été signalés. Souhaitez-vous que nous les conservions? Et si oui, comment souhaitez-vous que nous encodions les vieilles références et les nouvelles? En effet, il me semble que je ne repère que l'emploi de <corr> dans la dtd.

Merci.

**Comment by Jean-Baptiste-Camps** [comment]
Gardez les nouvelles. Si vous voulez être très précise, vous pouvez éventuellement utiliser `choice` avec `sic` et `corr`.

**Comment by ajaniak** [comment]
Les filles, j'ai donc décidé de conserve le schéma Choice, sic et corr pour la résolution des span coquille avec les expressions régulières c'es très rapide à résoudre.

**Comment by DUREAULT** [comment]
Ok j'en prends note pour la suite.

**Comment by ArmaneJM** [comment]
Merci je m'alignerai

**Comment by ArmaneJM** [comment]
Je me permet de fermer cette issue résolue :)
