### ISSUE TITLE
#2 Au sujet de l'encodage du texte d'Aymeri de Narbonne

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/geste#2]
Bonjour, 

Le dossier Aymeri de Narbonne contient une  version manuscrite et une version éditée : faut-il encoder seulement la version éditée, à l'instar des autres dossiers, ou les deux ?

Merci à vous, 

Ella.

**Comment by ajaniak** [comment]
Ella, 

Pour répondre à ton issue #2, il s'agit de deux textes différents. 

Bon courage.
