### ISSUE TITLE
Pull request pour front du texte Doon de la Roche

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/geste#20]
Hello ! 
Juste une nouvelle issue pour dire que je vous envoie mes métadonnées !

**Comment by ajaniak** [comment]
ok

**Comment by DUREAULT** [comment]
Non pardon mon front !!!

**Comment by ajaniak** [comment]
Ella je remarque que tu as des lb dans le début de ton intro... on est bien d'accord qu'on les garde pour les pages de titres mais qu'on n'en met pas dans le front et dans le back?

**Comment by DUREAULT** [comment]
Yes, je ne les ai pas encore enlevées... Je préférais rester sur mes gardes... 
Je les enlève demain matin !

**Comment by ajaniak** [comment]
je n'ai pas fait mes notes comme toi... tu intègres des p alors que je me suis contentée de la balise note

**Comment by ajaniak** [comment]
tu as typé la première div dans ta div intro et pas les autres, est-ce que c'est normal?

**Comment by DUREAULT** [comment]
Je les ai enlevées, je fais une pull request !

**Comment by DUREAULT** [comment]
J'ai enlevé le typage pour ma première div d'introduction : à moins qu'on détermine une forme de normalisation, donner un titre à certains chapitres semble beaucoup plus arbitraire parfois.

**Comment by DUREAULT** [comment]
Pour les quote, on s'était dit avec Armâne : une quote = un p.
J'aurais dû le dire ici. Je vais faire un petit mémo pour se rappeler nos normes d'encodage !

**Comment by DUREAULT** [comment]
Pour finir, j'ai accepté ta pull request (promis j'essaye de tout mettre dans un mail la prochaine fois!)

**Comment by ajaniak** [comment]
Je pensais qu'on devait harmoniser notre encodage sur les textes déjà encodé dans le projet geste!

**Comment by DUREAULT** [comment]
J'ai tenté d'adapter les lb en p...
Je change en ce cas.

**Comment by DUREAULT** [comment]
@ArmaneJM : je me suis trompée sur les quote : il n'y a pas de p en fait, désolée !

**Comment by ajaniak** [comment]
je disais pas qu'il fallait changer immédiatement ... j'ouvrais une discussion sur la question!

**Comment by DUREAULT** [comment]
D'ailleurs je parle des note en parlant de quote, mais c'est valable pour les deux en fait... Ok ok, de toute façon a priori Armâne va me maudire...
Je trouvais que ça faisait sens de remplacer les lb par des p dans la mesure où l'on n'encode a priori pas les lb pour le front.

**Comment by ajaniak** [comment]
Après c'est valable dans le schéma.. Cela serait peut-être bien d'essayer de voir JBCamps pour savoir ce qu'il attend dans ce domaine là exactement...

**Comment by DUREAULT** [comment]
Oui ce serait super! 
@Jean-Baptiste-Camps : seriez-vous d'accord pour organiser un petit temps de réflexion là-dessus?

**Comment by ArmaneJM** [comment]
Je ne vais maudire personne Ella ! haha. Enlever les p contenus dans les note ne va pas être une tâche bien compliquée ;). Quant aux lb je les conserve pour l'instant. A voir. Seriez vous dispo demain entre le cours de XQuery et le cours d'anglais? Cela pourrait faire une bonne session de travail (il y a 5h entre les deux). Merci :)

**Comment by DUREAULT** [comment]
Parfait pour demain ! 
Je te réponds ici pour la question des title : en effet, peut-être que title est un peu fort mais dans le document cela répondait à une découpe du texte un peu particulière... A voir ensemble peut-être demain ?

**Comment by ajaniak** [comment]
C est bon pour moi demain
