### ISSUE TITLE
Encodage de la numérotation des lignes

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/geste#25]
Peut-être cela a-t-il déjà été mentionné dans une autre issue mais comme le réseau est un peu embourbé, j'ouvre une nouvelle issue.
Avez-vous et si oui, comment, la numérotation des lignes de l'édition originale dans le body ?

Merci d'avance! :)

**Comment by ajaniak** [comment]
La numerotation des vers doit être faite par xsl d après le Readme du projet. J ai commencé à me pencher sur la question mais pour le moment je n ai pas beaucoup avancé!

**Comment by DUREAULT** [comment]
Oui je sais mais ce qui signifie en fait qu'on abandonne la numérotation de l'original ? #drame

**Comment by ajaniak** [comment]
Je pense que oui puisqu on favorise les laisses

**Comment by ArmaneJM** [comment]
J'ai enlevé la numérotation des lignes également pour ma part.

**Comment by ArmaneJM** [comment]
Je me permet de fermer cette issue la question de la xsl ayant été mentionnée dans l'issue #32
