### ISSUE TITLE
Balisage des vers dans le body

### ISSUE THREAD

**Issue by ArmaneJM** [Chartes-TNAH/geste#27]
Bonjour les filles,

J'ai quelques questions : tout d'abord, je ne peux pas mettre de texte directement dans une balise `<l>` (nous avions déjà évoqué ce problème sans trouver de solution). Du coup mon fichier est invalide et ne passera pas le test Travis. 
Ensuite, j'ai machinalement imbriqué les balises ainsi :`<lg type="laisse><l><lb/></l><l><lb/></l></lg>` alors que dans l'exemple, l'imbrication se trouve comme suit : `<lg type="laisse><lb/><l></l><lb/><l></l></lg>`.
Faut-il remédier à ça d'après vous? 

Merci et à tout à l'heure :)

**Comment by ajaniak** [comment]
J'ai pris le même schéma d'imbrication que toi pour le coup.

**Comment by ajaniak** [comment]
Pardon j'ai oublié de repondre à la première partie. Pour le moment, aucun de nos documents n'est valide. On doit demander la xslt de partition des mots de JBCamps.

**Comment by ArmaneJM** [comment]
Ok merci pour l'info ! Du coup on va  attendre l'avis de @DUREAULT pour prendre une décision pour le balisage histoire qu'on s'accorde toutes ;-)

**Comment by DUREAULT** [comment]
Je suis calée sur le même schéma.

**Comment by ArmaneJM** [comment]
OK je ferme donc cette issue. :)
