### ISSUE TITLE
Signification d'une balise dans le code html du body

### ISSUE THREAD

**Issue by ArmaneJM** [Chartes-TNAH/geste#28]
Bonjour @Jean-Baptiste-Camps ! 

Je me retrouve confrontée à un type de mise en page spécifique à mon édition. A 11 reprise exactement, il y a un alinéa sans saut de ligne le précédent (auquel cas il s'agirait du début d'une laisse). Dans le code html, cela est notifié ainsi `<span style="display:inline-block;min-width:1.0em">`, tandis qu'un début de laisse l'est ainsi `<span class="mw-poem-indented" style="display: inline-block; margin-left: 1em;">`. Dois-je conserver dans mon code xml cette spécificité ? 

Merci :)

<img width="649" alt="capture d ecran 2018-02-06 a 17 30 14" src="https://user-images.githubusercontent.com/33479582/35871183-dcf7f1f4-0b63-11e8-9c98-e5d55b493b2d.png">

**Comment by Jean-Baptiste-Camps** [comment]
L'éditeur ne s'en explique pas dans l'introduction ? Est-ce une manière de sa part de mettre la poussière sous le tapis quand il se demande s'il faut changer de laisse ou pas ? Si ce n'est pas expliqué, mettez juste un petit commentaire aux endroits en question.

**Comment by ArmaneJM** [comment]
Je n'ai pas trouvé d'explications dans l'introduction. Je met donc ce commentaire à chacune de ces occurrences : `<!-- retrait en début de ligne -->`
