### ISSUE TITLE
#3 métadonnées

### ISSUE THREAD

**Issue by ArmaneJM** [Chartes-TNAH/geste#3]
Bonjour, 

Comme discuté lors de notre première réunion, il serait bon de se répartir les textes pour l'encodage des métadonnées. Compte tenu de l'issue #2, nous choisissons de laisser côté pour le moment le dossier MortAymC. 
L'une de vous a-t-elle une préférence ? 

Merci

**Comment by DUREAULT** [comment]
Coucou Armâne, 

Je me propose pour le dossier Doon_de_la_roche.

A plus, 

Ella.

**Comment by ajaniak** [comment]
Les filles, 

Je peux m'occuper d'Aymeri de Narbonne, si cela convient à tout le monde. 

Bonne journée

**Comment by ArmaneJM** [comment]
Je me charge donc de Huon de Bordeaux. 

Bon courage !

**Comment by ArmaneJM** [comment]
Au fait, @ajaniak de quel texte d'Aymeri de Narbonne parles-tu ?

Merci d'avance pour ta réponse ! :)

**Comment by ajaniak** [comment]
@ArmaneJM, je prends la Mort d'Aymeri de Narbonne, dossier MortAymC. 
Je m'excuse de mon manque de clareté.

**Comment by ajaniak** [comment]
Bonjour les filles, 

je vais faire les métadonnées du dernier fichier.

**Comment by ajaniak** [comment]
suite à la pull request #21, je ferme cette issue.
