### ISSUE TITLE
XSL pour numérotation des laisses et le découpage en mots. 

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#32]
Bonjour @Jean-Baptiste-Camps , 

Pourriez-vous nous fournir les feuilles xsl pour la numérotation des laisses et le découpage des vers en mots pour que nous puissions essayer des les faire tourner? 

Merci

**Comment by ajaniak** [comment]
A priori, j'ai réussi à les faire tourner sur ed_MortAymC.xml ed_AimeriD.xml. Toutefois, pour le moment je conserve les fichiers de toutes les étapes: ed_MortAymC.xml étant le fichier initial, ed_MortAymC_token.xml le fichier après tokenisation et ed_MortAymC_token_num.xml le fichier après numérotation. Je vais faire une pull roquets avec les fichiers pour que vous les confirmiez.

**Comment by DUREAULT** [comment]
Coucou Axelle ! J'ai mergé ta PR et je ferai comme toi pour les fichiers.

**Comment by ajaniak** [comment]
Ok tu me diras si tu as besoin d aide pour la faire tourner. On comparera nos résultats pour savoir si on peut ne conserver que le fichier final!

**Comment by ArmaneJM** [comment]
Coucou ! J'ai essayé de faire tourner les xsl en suivant ce processus [https://www.soliantconsulting.com/blog/tricks-from-the-command-line-xsltproc-and-xmllint] . 
Toutefois, un message d'erreur apparait dans le terminal : 
`macbook-pro-de-armane:Huon_de_Bordeaux armanemagnier$ xsltproc workflow_numerotation.xsl ed_HuonG.xml > ed_HuonG_numerotation.xml
XPath error : Invalid expression
/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc[1]/child::element()[1]/@xml:id
                                                                     ^
compilation error: file workflow_numerotation.xsl line 19 element value-of
xsl:value-of : could not compile select expression '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc[1]/child::element()[1]/@xml:id'
macbook-pro-de-armane:Huon_de_Bordeaux armanemagnier$ xsltproc workflow_tokenization_quasi_fonctn.xsl ed_HuonG.xml > ed_HuonG_tokenizationn.xml
warning: failed to load external entity "workflow_tokenization_quasi_fonctn.xsl"
cannot parse workflow_tokenization_quasi_fonctn.xsl`

Le nouveau fichier.xml se crée, mais il est vide...

Pourrions nous voir ensemble demain comment tu es procédé @ajaniak s'il te plait ? J'admet avoir un peu de mal...

**Comment by ajaniak** [comment]
Pas de souci, on regarde ça tout à l heure! Je pense avoir une piste sur ton problème.

**Comment by ajaniak** [comment]
Puisque tout le monde sait maintenant faire tourner l'xslt, je ferme l'issue.
