### ISSUE TITLE
Nettoyage du body

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/geste#34]
Coucou les filles, 

Achevant de nettoyer mon body, je viens de voir que ce que je pensais être des corrections mentionnées par le code HTML sont en réalité des rendus d'élision dans le code lors de la numérisation du papier et du passage au texte sur Wikipédia. 
Je m'explique avec deux photos : 
<img width="965" alt="capture d ecran 2018-02-10 a 08 55 21" src="https://user-images.githubusercontent.com/33367741/36060010-63315484-0e40-11e8-8c48-7b77f4fe2012.png">
<img width="801" alt="capture d ecran 2018-02-10 a 08 57 23" src="https://user-images.githubusercontent.com/33367741/36060016-729cbf8a-0e40-11e8-956f-d23b42ea1c2e.png">

Je pense que vous n'y verrez pas d'inconvénient mais je le dis au cas où l'un de vous rencontrerait ce cas-là. On en avait également parlé avec @ajaniak.
Bon week-end à vous!

**Comment by DUREAULT** [comment]
P.S. : je nettoie bien sûr en respectant l'édition originale

**Comment by ArmaneJM** [comment]
J'ai procédé de la même façon ! :)

**Comment by DUREAULT** [comment]
Je ferme cette issue désormais résolue !
