### ISSUE TITLE
#4 Nettoyer les dossiers

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#4]
Bonjour à toutes,

En lien avec l'issue #3, nous pourrions peut-être faire un peu de nettoyage dans les dossiers, en particulier pour ceux issus de wikisource. 
Qu'en pensez-vous? 

Axelle

**Comment by DUREAULT** [comment]
Axelle, 
Oui je suis d'accord avec toi.

**Comment by ArmaneJM** [comment]
Je propose que chacune nettoie le dossier du texte dont elle s'occupe des métadonnées comme convenu dans l'issue #3 si cela va à tout le monde ? 
J'attend confirmation de votre part, merci :)

**Comment by DUREAULT** [comment]
Ok !

**Comment by DUREAULT** [comment]
👍

**Comment by ajaniak** [comment]
C'est une bonne idée :)
