### ISSUE TITLE
Numérotation des laisses Doon et Huon

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#43]
Les filles, 

si quelqu'un a le temps, il faudrait faire la numérotation des laisses sur le texte de Huon et faire la correction de la numérotation sur Doon.

**Comment by ArmaneJM** [comment]
J'y viens pour Huon, j'ai quelques corrections à faire auparavant :)

**Comment by ArmaneJM** [comment]
Juste pour préciser, mes laisses n'étant pas numérotées dans le corps du texte, j'ajoute juste un attribut xml:id et pas un n, n'est-ce pas ?

**Comment by ajaniak** [comment]
oui c'est un xml:id sous la forme: L_000. @DUREAULT tu confirmes?

**Comment by ajaniak** [comment]
Merci à toutes pour votre réactivité sur la question
