### ISSUE TITLE
Petites erreurs suite à la tokenization 

### ISSUE THREAD

**Issue by ArmaneJM** [Chartes-TNAH/geste#44]
Bonjour, j'ai deux petites erreurs qui sont apparues, toutes deux liées à la présence d'italique visiblement repéré par la xsl. Je m'explique en joignant le code : 

`<l n="6764"><w><lb/><i>Se tu i gis<pc type="supplied">,</pc> se me puist Dix salver<pc type="supplied">,</pc></i></w></l>
<l n="6765"><w><lb/><i>Tu en seras honnis et vergondés<pc type="supplied">.</pc></i></w><pc type="supplied">»</pc></l>`

J'ai constaté que la balise `<i>` n'apparait pas dans le modèle ODD, cependant une balise `<hi>` peut contenir des `<w>` et signifie une mise en valeur du texte sans en préciser la forme. J'aboutirais ainsi à ceci : 

`<l n="6764"><lb/><hi><w>Se</w> <w>tu</w> <w>i</w> <w>gis</w><pc type="supplied">,</pc> <w>se</w> <w>me</w> <w>puist</w> <w>Dix</w> <w>salver</w><pc type="supplied">,</pc></hi></l>
<l n="6765"><lb/><hi><w>Tu</w> <w>en</w> <w>seras</w> <w>honnis</w> <w>et</w> <w>vergondés</w><pc type="supplied">.</pc></hi><pc type="supplied">»</pc></l>`

Je peux éventuellement signaler l'italique dans un commentaire.... qu'en pensez-vous ?

Merci pour vos retours :)

**Comment by ArmaneJM** [comment]
[https://fr.wikisource.org/wiki/Page:Anonyme_-_Huon_de_Bordeaux,_chanson_de_geste.djvu/340](url)

Histoire de visualiser la chose ;)

**Comment by ArmaneJM** [comment]
https://fr.wikisource.org/wiki/Page:Anonyme_-_Huon_de_Bordeaux,_chanson_de_geste.djvu/340

Histoire de visualiser la chose

**Comment by ajaniak** [comment]
Est-ce que tu ne pourrais pas utiliser une balise hi avec un attribut rend italic?

**Comment by ArmaneJM** [comment]
Les valeurs de l'attribut rend dans `<hi>` ne comprennent pas italic malheureusement... j'aurais aimé

**Comment by ajaniak** [comment]
est-ce que tu sais pourquoi l'éditeur à mis ces vers la en italique? La raison pourrait peut-être te permettre de trouver une manière de contourner le problème...Sinon tu vois avec @Jean-Baptiste-Camps pour qu'il prenne en compte ton cas de figure et l'ajoute au modèle au ODD.

**Comment by DUREAULT** [comment]
Moi j'avais choisi la balise emph + un typage rend="italique"

**Comment by DUREAULT** [comment]
Soit `<emph rend="italic">...</emph>`

**Comment by ArmaneJM** [comment]
D'accord, dans ce cas je dois englober tout le vers dans `<emph>` cette balise ne pouvant être contenue dans `<l>` mais pouvant le contenir selon le modèle odd... Dans mon cas, pas de soucis, les deux vers sont en italiques dans leur globalité. Je fais comme ça ? :)

**Comment by ArmaneJM** [comment]
J'ai parlé trop vite, même là le fichier est invalide...

**Comment by DUREAULT** [comment]
Emph ne fonctionne pas dans le vers  ?

**Comment by ajaniak** [comment]
Tu peux d'uniformiser avec l'encodage d'Ella, je pense que c'est une bonne solution. Mais  je n'ai pas eu le cas de figure alors je vous laisse juger.

**Comment by ajaniak** [comment]
tu n'as pas eu d'italique dans le body @DUREAULT ?

**Comment by ArmaneJM** [comment]
J'aimerais bien, ça serait parfait, mais cela ne semble pas fonctionner dans mon cas...

**Comment by DUREAULT** [comment]
Non

**Comment by DUREAULT** [comment]
Et si tu fais un rend dans le vers ?

**Comment by ArmaneJM** [comment]
non... vraiment j'ai tenté tout ça, je ne parvient pas à signifier l'italique dans le body. :/

**Comment by ArmaneJM** [comment]
Je laisse peut être `<hi>` pour l'instant, en attendant l'avis de @Jean-Baptiste-Camps  ?

**Comment by DUREAULT** [comment]
Je n'avais des italiques que pour la foliotation et les notes. 
Comme j'ai déjà un problème pour l'attribut des balises de foliotation, je préférais attendre.

**Comment by ArmaneJM** [comment]
D'accord, je n'ai pas de foliation dans mon texte... Bon courage :)

**Comment by DUREAULT** [comment]
Merci! :)

**Comment by ajaniak** [comment]
Les filles, 
est-ce que vous avez des mots vides à la suite de votre tokenisation aussi? si oui, comment avez-vous gérer la question? 
Merci

**Comment by ArmaneJM** [comment]
J’ai supprimé les balises ouvrantes et fermantes dans mon cas :) c’etait Souvent en début de ligne, sûrement une erreur du fait qu’il y avait parfois des espaces

**Comment by ajaniak** [comment]
je ne suis pas sûre de ce que tu veux dire... tu as juste supprimé ces balises vides avant la numérotation?

**Comment by ajaniak** [comment]
du coup vous avez gérer comment cet enchaînement la `<w><lb/></w><pc type="supplied">«</pc>`?

**Comment by ArmaneJM** [comment]
J'ai utilisé une regex pour supprimer le `w` entourant le <lb/>, ce qui donne : `<lb/><pc type="supplied">«</pc>`

**Comment by ajaniak** [comment]
J'ai utilisé le même schéma que toi.

**Comment by ArmaneJM** [comment]
Je viens de réaliser en comparant nos fichiers que lorsque j'ai effectué la numérotation suite à la tokenization, mes mots `<w>` n'ont pas été numérotés contrairement aux tiens....

**Comment by ArmaneJM** [comment]
@ajaniak @DUREAULT vous avez effectué quelque chose d'autre pour obtenir les xml:id dans les w ?

**Comment by ajaniak** [comment]
non les xml:id sont automatiques.

**Comment by ArmaneJM** [comment]
Ok décidément... J'avoue ne pas vraiment comprendre pourquoi cela n'a pas fonctionné dans mon cas, les vers ont pourtant été correctement numérotés...

**Comment by ajaniak** [comment]
Tu as peut-être eu un problème dans le parsage de tes noeuds?

**Comment by DUREAULT** [comment]
Ils se sont aussi générés chez moi.

**Comment by ajaniak** [comment]
@ArmaneJM, est-ce que tu peux mettre la dernière version de ton fichier tokenisé pour que je jette un coup d'oeil, s'il te plait?

**Comment by ArmaneJM** [comment]
Tout de suite ! Je fais une pull roquets

**Comment by ArmaneJM** [comment]
Merci à toutes pour votre coup de main, l'édition est maintenant toute belle ! (j'espère), elle passe haut la main tous les tests en tout cas  !

**Comment by ajaniak** [comment]
Je t'en  prie du coup je ferme l'issue.
