### ISSUE TITLE
xml-lang pour Capitans

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#49]
Bonjour à toutes et @PonteIneptique, 

Quelqu'un pourrait-il me repréciser les xml-lang des fichiers cts de Capitans qui correspondent au fro et au fre? J'ai une petite hésitation sur les endroits où ils doivent être mobilisés malgré la lecture des guidelines. 

Merci.

**Comment by DUREAULT** [comment]
Dans la suite de cette question @PonteIneptique , que met-on dans `<ti:description>` ?

Merci d'avance !

**Comment by ArmaneJM** [comment]
Et peut-on enlever  `<ti:translation>` et `<ti:commentary>` @PonteIneptique ? Il me semble qu'ici nous n'en avons pas...  merci pour votre réponse ! :)

**Comment by ajaniak** [comment]
pour le `<ti:descrpition>` j'ai mis le contenu de la page de titre, qu'en pensez-vous?

**Comment by PonteIneptique** [comment]
- Page de titre / description : oui
- translation et commentary : bien sur.
- xml:lang pour tout sauf ti:work indique la langue d'expression de texte : `<a xml:lang="fre">Signifie que je suis en francais</a>`
- pour ti:work, xml:lang indique la langue de l'oeuvre

**Comment by DUREAULT** [comment]
Merci beaucoup. Nous avions procédé ainsi donc c'est parfait !

**Comment by ajaniak** [comment]
Okay les filles,
je me demande s'il ne faut pas aussi une numérotation n dans les laisses en plus de la numérotation que nous avons déjà mise en place, afin que cela match avec le schéma xpath préconiser par Capitains. Est-ce que vous comprenez les Refsdec comme moi?

**Comment by ajaniak** [comment]
Je retire ce que je viens de dire! en relisant le readme, la référence aux vers est demandé par celles aux laisses. Toutes mes excuses. 
Par contre, comme les vers ne sont pas le premier niveau du noeud, comment vous comprenez la formulation des niveaux?

**Comment by ajaniak** [comment]
Les filles, 
J'ai résolu la question des URN information et des xml-lang pour la validation Capitains. Ces informations doivent etre contenu au niveau de TEI/text.

**Comment by ajaniak** [comment]
@DUREAULT, tu pouvais la laisser fermer. Je pense que la question des nommages de fichiers Capitains était abordée dans l'issue #29 non?

**Comment by DUREAULT** [comment]
Pardon je rouvre l'issue car ce n'est toujours pas très clair pour moi : Axelle tu as mis "fre" pour ton ti:title (Mort Aymeri) et Armâne "fro". J'avais également mis "fro" mais si je comprends bien, il faut surtout changer quelque chose au niveau de la TEI ?

**Comment by ajaniak** [comment]
ce que j'ai compris d'après les explications de Clérice, c'est que tu mets fro quand on fait référence à l'oeuvre intellectuelle qui est médiévale, mais quand tu fais référence à l'oeuvre dans son édition il faut mettre fre. Du coup, il me semblait que le titre de la geste datait plutôt de notre période que de l'oeuvre originale, mais je peux changer si vous considérez toutes les deux que ça n'est pas le cas!

**Comment by ajaniak** [comment]
au noeud TEI/text il faut ajouter un xml-lang et l'urn, il est manquant dans ton fichier il me semble. tu n'as pas eu d'erreur sur le Capitains Validator pour URN informations?

**Comment by DUREAULT** [comment]
Je ne considère rien mais je soulevais l'idée. 
J'ai également eu un problème pour l'URN. Ceci explique pourquoi j'ai voulu rouvrir l'issue.

**Comment by DUREAULT** [comment]
Je m'aligne sur toi car je pense que c'est plus logique et je renvoie mon fichier complété avec l'URN.

**Comment by ArmaneJM** [comment]
Je fais de même pour la langue

**Comment by ajaniak** [comment]
Par contre, je crois que j'ai fait une erreur sur le xml:lang dans le noeud tei/text il doit être en fro et pas en fre. Je pense c'est ce que veut signifier l'erreur "failed correct xml:lang attribute" de travis

**Comment by DUREAULT** [comment]
Du coup, je remerge avec le bon xml:lang.
