### ISSUE TITLE
#5 interrogations sur les informations contenues dans les métadonnées

### ISSUE THREAD

**Issue by ArmaneJM** [Chartes-TNAH/geste#5]
Bonjour, 

Nous aimerions savoir à quoi correspondent dans la colonne lieu_manuscrit du tableau de métadonnées les lieux cités sous les formes de "bourg", "pic." et "traits bourg". Nous supposons Bourgogne et Picardie mais aimerions avoir confirmation. 

Merci

**Comment by ajaniak** [comment]
Bonjour, 

En lien avec la remarque de @ArmaneJM  en #5, quelle valeur de certitude pensez-vous que nous devions attribuer à l'attribut cert aux remarques formulées par le DEAF sur les dates et les localisaton issus du document csv? 

Merci

**Comment by ArmaneJM** [comment]
@ajaniak , j'imagine qu'en l'absence d'information sur la certitude il faut mettre "unknown". Je me trompe peut être ceci dit.

**Comment by Jean-Baptiste-Camps** [comment]
Je vote pour 'unknown' également, sauf si vous vous sentez d'évaluer la marge de confiance des localisations données par le DEAF.

Les formes de type 'bourg.' ou 'traits pic.', etc., sont celles données par la bibliographie du DEAF (Frankwalt Möhren et Elena Miller, Dictionnaire Étymologique de l’Ancien Français: Bibliographie, complément bibliographique. Elektronische Fassung (DEAFBiblÉl), Heidelberg, 2010-…, http://www.deaf-page.de/bibl_neu.php ). En gros, ça veut dire: '[écrit dans une scripta/un dialecte] bourg.[uignonne]' ou 'avec des traits picards', etc. et on présuppose généralement (en fait, rien ne le garantit) que ça corresponde au lieu d'origine du manuscrit (si c'est écrit en bourguignon, ça doit avoir été écrit en Bourgogne).

Si vous voulez, vous pouvez reprendre les valeurs telles quelles pour le moment.
