### ISSUE TITLE
Normalisation des <l> 

### ISSUE THREAD

**Issue by ArmaneJM** [Chartes-TNAH/geste#54]
Salut les filles ! Juste une petite issue pour mettre au point une norme d'encodage pour les `<l>` dans les laisses.
Pour ma part j'ai choisi de faire ainsi : 

`<l><lb/><w></w></l>`

Avec le lb à l'extérieur du mot donc ce qui n'est pas la cas chez vous, mais qui est peut être un peu plus pertinent... 
Du coup concrètement ça donne quelque chose comme ça par exemple (pas d'inquiétude
il manque la numérotation des mots, ça arrive) : 

`<l n="47"><lb/><w>Et</w> <w>autretant</w> <w>qui</w> <w>furent</w> <w>despensier</w><pc type="supplied">.</pc></l>`

Dites moi ce que vous en pensez ! Bisous :)

**Comment by ajaniak** [comment]
Je me suis alignée sur toi.

**Comment by DUREAULT** [comment]
Pareil!

**Comment by ajaniak** [comment]
Nickel, une issue de plus à fermer.
