### ISSUE TITLE
pb fichier xml pour dossier 60310 dans data

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#59]
@ArmaneJM, je ne sais pas si tu as vu mon commentaire dans ma pull request mergée par Ella, cette nuit. Il y a deux fichiers xml dans le dossier 60310. Peux-tu nous dire lequel est le bon? 

Merci :)

**Comment by ArmaneJM** [comment]
Oui je vois, je suis juste allée me coucher un moment donné hier soir haha. Merci pour la correction dans le fichier cts, je m'occupe des dernières petites choses !

**Comment by ArmaneJM** [comment]
Le problème est résolu, une pull request vous attend, je clos l'issue ;)
