### ISSUE TITLE
#6 Encodage de la langue dans les métadonnées

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/geste#6]
Bonjour, 

Je m'interroge sur les langues utilisées pour chaque texte : où trouvons-nous les informations ? 

Merci, 

Ella Duréault.

**Comment by Jean-Baptiste-Camps** [comment]
Ce sont, sauf cas particuliers, les mêmes que pour la localisation du manuscrit (cf. Frankwalt Möhren et Elena Miller, Dictionnaire Étymologique de l’Ancien Français: Bibliographie, complément bibliographique. Elektronische Fassung (DEAFBiblÉl), Heidelberg, 2010-…, http://www.deaf-page.de/bibl_neu.php.). Les introductions des textes peuvent aussi donner parfois quelques indications supplémentaires.
