### ISSUE TITLE
#8 titre pour ed_AimeriD

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/geste#8]
Bonjour à tous, 

après avoir commencé l'encodage du ed_AimeriD #3 , j'ai quelques questions dont je n'ai pas trouvé de résolution dans l'ODD, ni dans l'exemple. Ce ficher possède un titre composé: Aymeri de Narbonne : chanson de geste  : publiée d'après les manuscrits de Londres et de Paris. Pour le moment, j'ai mis Aymeri de Narbonne dans le <title type="main">. Dans la mesure où l'encodage conserve la mise en page et les structures de la version papier, il me semble qu'il faut conserver toutes ces informations.  Nous pourrions les mettre tout bêtement dans le titre, mais je ne suis pas certaine car les manuscripts apportent des références intéressantes qui mériteraient d'être mis en valeur. Qu'en pensez-vous? Auriez-vous une idée de la manière dont nous pourrions les intégrer? 

Merci

**Comment by ajaniak** [comment]
Pourriez-vous aussi m'indiquer la manière dont vous avez encoder la collection de l'ouvrage? l'avez-vous conservé ou supprimé? Pour le moment, je l'ai intégré dans un imprint, puisque la balise serieStmt n'est pas valide dans le schéma ODD. 

Merci

**Comment by ArmaneJM** [comment]
Salut Axelle ! Pour ma part j'ai mit deux titres, un main comme le tien avec juste **<title type="main">Huon de Bordeaux</title>** et un sub **<title type="sub">Numérisation de l'édition de Guessard de 1860</title>** avec les précisions quand à la version que nous encodons. En espérant que cela peut t'aider...
A bientôt :)

**Comment by DUREAULT** [comment]
1. J'ai fait la même chose qu'Armâne pour le titre. Tu peux mettre plusieurs titles à la suite avec le premier ayant pour attribut "main", les suivants ayant pour attribut "sub". 

2. J'ai également intégré dans un imprint le nom de la collection avec : 
<imprint>
<publisher>Société des anciens textes français (65)</publisher> (que j'ai récupéré dans le fichier de métadonnées)
<pubPlace>Paris</pubPlace>
</imprint>

**Comment by ajaniak** [comment]
c'est bon, on a encodé les éléments de la même manière.
